services:
  # ğŸŒ Backend (.NET API)
  - type: web
    name: my-backend
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    runtime: docker
    envVars:
      # El backend necesita saber el origen del frontend para CORS
      - key: FRONTEND_URL
        fromService:
          type: web
          name: my-frontend
          property: url
      - key: MONGO_URI
        sync: false

  # ğŸŒ Frontend (Next.js)
  - type: web
    name: my-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    dependsOn:           # ğŸ‘ˆ asegura que el backend exista antes de build del front
      - my-backend
    envVars:
      # El front necesita la URL del backend ya resuelta
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: my-backend
          property: url
